name: pytest and terraform validation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test_pokemon_quiz_app:
    runs-on: ubuntu-latest
    permissions:             # GITHUB_TOKENの権限を指定 
      contents: read         # ソースコードの読み込みを許可

    steps:
      - uses: actions/checkout@v3           # コードを取得
      - uses: hashicorp/setup-terraform@v3  # Terraformのセットアップ
      - uses: actions/setup-python@v4       # Python セットアップ
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -r docker/requirements.txt

      - uses: aws-actions/configure-aws-credentials@v4  # クレデンシャルの環境変数を設定
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: |
          export PYTHONPATH=$(pwd)
          pytest
      - run: |
          terraform init
          terraform fmt -check -no-color -recursive
          terraform validate
          # terraform plan -no-color
